### ISSUE TITLE
Background image stretches undesirably on mobile browsers

### ISSUE THREAD

**Issue by przbetkier** [przbetkier/tuscan-frontend#53]
Adjust css styles to scale image properly on mobile web browsers like safari mobile/chrome mobile.

On desktop browsers background image behaves as intended:
![Screenshot 2019-10-24 at 14 06 25](https://user-images.githubusercontent.com/18195654/67484067-95650200-f667-11e9-9d64-19bb0b702529.png)

But on mobiles:
![72911831_515952788963294_1714507900400959488_n](https://user-images.githubusercontent.com/18195654/67484852-330d0100-f669-11e9-8db1-c5dddce2ab3a.jpg)

**Comment by pawelgraczyk** [comment]
Biore to! 🔥

**Comment by przbetkier** [comment]
> Biore to! 🔥

W przypadku gdybyś potrzebował postawić backend, a by były problemy to daj znać, bo nie mam w readme jeszcze opisanego dokładnie co i jak. Dzięki!

**Comment by pawelgraczyk** [comment]
> > Biore to! 🔥
> 
> W przypadku gdybyś potrzebował postawić backend, a by były problemy to daj znać, bo nie mam w readme jeszcze opisanego dokładnie co i jak. Dzięki!

aktualnie mam problem z odpaleniem tego na browserstacku

**Comment by pawelgraczyk** [comment]
> > > Biore to! 🔥
> > 
> > 
> > W przypadku gdybyś potrzebował postawić backend, a by były problemy to daj znać, bo nie mam w readme jeszcze opisanego dokładnie co i jak. Dzięki!
> 
> aktualnie mam problem z odpaleniem tego na browserstacku (symulacja mobilki) bo nie mogę zdiagnozować błędu :/

**Comment by przbetkier** [comment]
Mówisz o produkcyjnej (https://tuscan.pro) stronce?
U mnie działa na browserstacku 🤔 

![Screenshot 2019-10-24 at 14 57 37](https://user-images.githubusercontent.com/18195654/67487696-ab29f580-f66e-11e9-9871-fa9a6d3e31a1.png)

**Comment by pawelgraczyk** [comment]
localhost na iphone :/ daj znak jak odpalić serwer, bo rozumiem ze tło psuje się na profilu gracza?

**Comment by przbetkier** [comment]
Teoretycznie podłączenie się do środowiska prod nie spowoduje żadnego problemu, spróbuj w environment.ts wrzucić link 'https://api.tuscan.pro' zamiast localhost dla ApiEndpoint.
Póki co jeszcze pozwalam na backendzie uderzać skądkolwiek, więc na Twoje potrzeby to może być quickfix

**Comment by pawelgraczyk** [comment]
Wrzucam szybki fix -> https://github.com/przbetkier/tuscan-frontend/pull/54

**Comment by przbetkier** [comment]
Na desktopie to nic nie zmienia, a browserstack lokalnie mi szwankuje, więc zmerguję to i sprawdzę na realnych urządzeniach :)

**Comment by przbetkier** [comment]
Deployed, jednak bez zmian
