### ISSUE TITLE
website version player stats are blank

### ISSUE THREAD

**Issue by Blacktail92** [przbetkier/tuscan-frontend#85]
I tried incognito (disables all extensions) but no good. Basically "Recent performance", "Recent matches" and "Recent teammates" fields are all blank.

**Comment by przbetkier** [comment]
Hello @Blacktail92

It looks like Faceit changed some JSON field names in their API response, which caused some errors for the newest matches. 

I already fixed it (on backend project), details here:
https://github.com/przbetkier/tuscan/commit/f84589d9f9f5c7330c9867513e38c031708d5e2b

Your profile on tuscan should now look as good as it was before:
https://www.tuscan.pro/player/Blacktail92

Thanks for your report and sorry for any inconvenience!
P.

**Comment by Blacktail92** [comment]
Thanks a lot :)
